/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Moneda.as).
 */

package entidadesbasicas.modelo.entidades
{

    [Bindable]
    public class MonedaBase {
	
            
            private var _codigo:String;
            private var _descripcion:String;

            [Bindable]
            public function get codigo():String{
                return this._codigo;
            }
            [Bindable]
            public function get descripcion():String{
                return this._descripcion;
            }
            [Bindable]
            public function set codigo(value:String):void{
                this._codigo = value;
            }
            [Bindable]
            public function set descripcion(value:String):void{
                this._descripcion = value;
            } 
    }
}