/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package entidadesbasicas.modelo.entidades
{

    [Bindable]
    [RemoteClass(alias="entidadesbasicas.modelo.Moneda")]
    public class Moneda extends MonedaBase {
    }
}